version: 1.0.{build}

environment:
  fast_finish: false
  allow_failures: true
  matrix:

    - job_name: Windows
      appveyor_build_worker_image: Visual Studio 2017
      job_group: Build

for:
  -
    matrix:
      only:
        - job_name: Windows

    clone_folder: c:\projects\source-engine
    install:
    - cmd: >-
        git submodule update --init --recursive
        
        ./waf configure -T release --build-game=cstrike --32bits --prefix=../buildok
    
# cache:
#   - c:\projects\*.zip -> appveyor.yml
#   - c:\projects\mysql-5.5 -> appveyor.yml
    build_script:
    - cmd: >-
        ./waf install
after_build:
  # Create archive
  - 7z a -t7z buildok.7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on c:\projects\buildok
  - appveyor PushArtifact buildok.7z
